/prisma_rover/diffdrive_node:
  ros__parameters:
    use_runge_kutta: false
    base_width: 0.48
    steps_per_meter: 4288.382
    swap_motors: true
    invert_motor_1: false
    invert_motor_2: false
    var_pos_x: 0.01
    var_pos_y: 0.01
    var_pos_z: 0.01
    odom_tf_name: "prisma_rover/odom"
    base_tf_name: "prisma_rover/base_footprint"
    namespace: "/prisma_rover"
    publish_tf: false

/prisma_rover/roboclaw_node:
  ros__parameters:
    serial_port: "/dev/ttyACM0"
    baudrate: 115200
    roboclaws: 1
    namespace: "/prisma_rover"
